nav:
- index.md
- 偏微分方程简介: 
  - PDEIntro/index.md  
  - PDE的定义: PDEIntro/PDEdef.md
- 四种重要的方程: 
  - FourPDEs/index.md
  - Laplace方程: FourPDEs/Laplace.md
- Sobolev 空间:
  - SobolevSpaces/index.md
  - 定义: SobolevSpaces/Definition.md
  - 逼近: SobolevSpaces/Approximation.md
  - 延拓: SobolevSpaces/Extensions.md
  - Hölder 空间: SobolevSpaces/HölderSpaces.md
  - Sobolev 不等式: SobolevSpaces/SobolevInequalities.md