nav:
  - index.md
  - CQHF:
    - CQHF/index.md
    - HTFDE: 
      - CQHF/HTFDE/index.md
      - Preliminaries: 
        - MultivaluedAnalysis: CQHF/HTFDE/Preliminaries/MultivaluedAnalysis.md
        - FractionalCalculus: CQHF/HTFDE/Preliminaries/FractionalCalculus.md