nav:
- index.md
- 仿射与凸集: AffineAndConvex/index.md
- 凸函数: 
  - ConvexFunction/index.md
  - 共轭函数: ConvexFunction/ConjugateFunction.md
- HW:
  - HW1: HomeWork/HW1.md
  - HW2: HomeWork/HW2.md
  - HW3: HomeWork/HW3.md
  - HW4: HomeWork/HW4.md