copyright: Copyright &copy; 2024-2025 qgdr</br>The website content is licensed under
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- index.md
- MathematicalAnalysis:
  - MathematicalAnalysis/index.md
  - "\u5B9E\u6570\u4E0E\u6781\u9650":
    - MathematicalAnalysis/RealandLimit/index.md
    - "\u6709\u9650\u8986\u76D6\u5B9A\u7406": MathematicalAnalysis/RealandLimit/compact.md
  - "\u66F2\u9762\u79EF\u5206":
    - MathematicalAnalysis/SurfaceIntegral/index.md
    - "Gauss-Green\u516C\u5F0F": MathematicalAnalysis/SurfaceIntegral/GaussGreen.md
- ConvexOptimization:
  - ConvexOptimization/index.md
  - "\u4EFF\u5C04\u4E0E\u51F8\u96C6": ConvexOptimization/AffineAndConvex/index.md
  - HW:
    - HW1: ConvexOptimization/HomeWork/HW1.md
    - HW2: ConvexOptimization/HomeWork/HW2.md
- PartialDifferentialEquations:
  - PartialDifferentialEquations/index.md
  - "\u504F\u5FAE\u5206\u65B9\u7A0B\u7B80\u4ECB":
    - PartialDifferentialEquations/PDEIntro/index.md
    - "PDE\u7684\u5B9A\u4E49": PartialDifferentialEquations/PDEIntro/PDEdef.md
  - "\u56DB\u79CD\u91CD\u8981\u7684\u65B9\u7A0B":
    - PartialDifferentialEquations/FourPDEs/index.md
    - "Laplace\u65B9\u7A0B": PartialDifferentialEquations/FourPDEs/Laplace.md
- Topology:
  - Topology/index.md
  - "\u62D3\u6251\u7A7A\u95F4":
    - Topology/TopoSpc/index.md
    - "\u5F15\u5165": Topology/TopoSpc/induct.md
  - "\u95ED\u96C6":
    - Topology/Closed/index.md
    - "\u95ED\u5305": Topology/Closed/closure.md
    - "\u6781\u9650": Topology/Closed/limit.md
  - "\u7D27\u6027":
    - Topology/Compact/index.md
- Test: test.md
plugins:
- search
- glightbox:
    auto_caption: false
    caption_position: bottom
    draggable: false
    effect: zoom
    height: auto
    loop: false
    slide_effect: none
    touchNavigation: true
    width: 100%
    zoomable: true
- mkdocstrings:
    handlers:
      python:
        paths:
        - src
site_author: qgdr
site_description: "\u6570\u5B66\u77E5\u8BC6\u6846\u67B6\u4E0E\u89C2\u70B9\u7406\u89E3"
site_name: My Docs
theme:
  extra:
    generator: false
    social:
    - icon: material/github
      link: https://github.com/qgdr
    status:
      new: "\u6700\u8FD1\u6DFB\u52A0"
  features:
  - announce.dismiss
  - content.action.edit
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - content.tooltips
  - navigation.tabs
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  font:
    code: Fira Code
    text: Noto Sans SC
  icon:
    logo: material/pi
  language: zh
  name: material
  palette:
  - primary: pink
    scheme: default
    toggle:
      icon: material/weather-night
      name: shift night
  - primary: green
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: shift day
