copyright: Copyright &copy; 2024-2025 qgdr</br>The website content is licensed under
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- index.md
- MathematicalAnalysis:
  - MathematicalAnalysis/index.md
  - "\u5B9E\u6570\u4E0E\u6781\u9650":
    - MathematicalAnalysis/RealandLimit/index.md
    - "\u6709\u9650\u8986\u76D6\u5B9A\u7406": MathematicalAnalysis/RealandLimit/compact.md
  - "\u66F2\u9762\u79EF\u5206":
    - MathematicalAnalysis/SurfaceIntegral/index.md
    - "Gauss-Green\u516C\u5F0F": MathematicalAnalysis/SurfaceIntegral/GaussGreen.md
- LinearAlgebra:
  - LinearAlgebra/index.md
  - SVD: LinearAlgebra/svd.md
  - "\u77E9\u9635\u8303\u6570": LinearAlgebra/MatrixNorm.md
- Topology:
  - Topology/index.md
  - "\u62D3\u6251\u7A7A\u95F4":
    - Topology/TopoSpc/index.md
    - "\u5F15\u5165": Topology/TopoSpc/induct.md
    - "\u95ED\u96C6": Topology/TopoSpc/closure.md
    - "\u6781\u9650": Topology/TopoSpc/limit.md
    - "\u7D27\u6027": Topology/TopoSpc/compact.md
- ConvexOptimization:
  - ConvexOptimization/index.md
  - "\u57FA\u7840\u7406\u8BBA":
    - "\u4EFF\u5C04\u4E0E\u51F8\u96C6": ConvexOptimization/Theory/AffineAndConvex.md
    - "\u51F8\u51FD\u6570": ConvexOptimization/Theory/ConvexFunction.md
    - "\u5171\u8F6D\u51FD\u6570": ConvexOptimization/Theory/ConjugateFunction.md
    - "\u6B21\u68AF\u5EA6": ConvexOptimization/Theory/SubGradient.md
  - "\u4F18\u5316\u7B97\u6CD5":
    - ConvexOptimization/Algorithms/Proximal.md
  - HW:
    - HW1: ConvexOptimization/HomeWork/HW1.md
    - HW2: ConvexOptimization/HomeWork/HW2.md
    - HW3: ConvexOptimization/HomeWork/HW3.md
    - HW4: ConvexOptimization/HomeWork/HW4.md
    - HW5: ConvexOptimization/HomeWork/HW5.md
- FiniteDifferenceMethods:
  - FiniteDifferenceMethods/index.md
  - "\u521D\u503C\u95EE\u9898":
    - FiniteDifferenceMethods/InitialValueProblems/index.md
    - "\u7EBF\u6027\u591A\u6B65\u6CD5": FiniteDifferenceMethods/InitialValueProblems/LinearMultistepMethods.md
- RealAnalysis:
  - RealAnalysis/index.md
  - "\u5377\u79EF":
    - RealAnalysis/Convolution/index.md
  - "\u903C\u8FD1":
    - RealAnalysis/Approximation/index.md
- FunctionalAnalysis:
  - FunctionalAnalysis/index.md
  - CompactOperators:
    - FunctionalAnalysis/CompactOperators/index.md
- PartialDifferentialEquations:
  - PartialDifferentialEquations/index.md
  - "\u504F\u5FAE\u5206\u65B9\u7A0B\u7B80\u4ECB":
    - PartialDifferentialEquations/PDEIntro/index.md
    - "PDE\u7684\u5B9A\u4E49": PartialDifferentialEquations/PDEIntro/PDEdef.md
  - "\u56DB\u79CD\u91CD\u8981\u7684\u65B9\u7A0B":
    - PartialDifferentialEquations/FourPDEs/index.md
    - "Laplace\u65B9\u7A0B": PartialDifferentialEquations/FourPDEs/Laplace.md
  - "Sobolev \u7A7A\u95F4":
    - PartialDifferentialEquations/SobolevSpaces/index.md
    - "\u5B9A\u4E49": PartialDifferentialEquations/SobolevSpaces/Definition.md
    - "\u903C\u8FD1": PartialDifferentialEquations/SobolevSpaces/Approximation.md
    - "\u5EF6\u62D3": PartialDifferentialEquations/SobolevSpaces/Extensions.md
    - "Sobolev \u4E0D\u7B49\u5F0F I": PartialDifferentialEquations/SobolevSpaces/SobolevInequalities.md
    - "H\xF6lder \u7A7A\u95F4": "PartialDifferentialEquations/SobolevSpaces/H\xF6\
        lderSpaces.md"
    - "Sobolev \u4E0D\u7B49\u5F0F II": PartialDifferentialEquations/SobolevSpaces/SobolevInequalities2.md
    - "Poincar\xE9 \u4E0D\u7B49\u5F0F": "PartialDifferentialEquations/SobolevSpaces/Poincar\xE9\
        .md"
    - "\u5DEE\u5546": PartialDifferentialEquations/SobolevSpaces/Difference.md
    - HW1: PartialDifferentialEquations/HW1.md
- FractionalDifferentialEquations:
  - FractionalDifferentialEquations/index.md
  - "\u5206\u6570\u9636\u5FAE\u79EF\u5206": FractionalDifferentialEquations/RLFIDF.md
- Research:
  - Research/index.md
  - CQHF:
    - Research/CQHF/index.md
    - HTFDE:
      - Research/CQHF/HTFDE/index.md
      - Preliminaries:
        - MultivaluedAnalysis: Research/CQHF/HTFDE/Preliminaries/MultivaluedAnalysis.md
        - FractionalCalculus: Research/CQHF/HTFDE/Preliminaries/FractionalCalculus.md
plugins:
- search
- glightbox:
    auto_caption: false
    caption_position: bottom
    draggable: false
    effect: zoom
    height: auto
    loop: false
    slide_effect: none
    touchNavigation: true
    width: 100%
    zoomable: true
- mkdocstrings:
    handlers:
      python:
        paths:
        - src
site_author: qgdr
site_description: "\u6570\u5B66\u77E5\u8BC6\u6846\u67B6\u4E0E\u89C2\u70B9\u7406\u89E3"
site_name: MTree
theme:
  custom_dir: overrides
  extra:
    generator: false
    social:
    - icon: material/github
      link: https://github.com/qgdr
    status:
      new: "\u6700\u8FD1\u6DFB\u52A0"
  features:
  - announce.dismiss
  - content.action.edit
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - content.tooltips
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  font:
    code: Fira Code
    text: Raleway
  icon:
    logo: material/pi
  language: zh
  name: material
  palette:
  - primary: pink
    scheme: default
    toggle:
      icon: material/weather-night
      name: shift night
  - primary: green
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: shift day
