nav:
- index.md
- 基础理论:
  - 仿射与凸集: Theory/AffineAndConvex.md
  - 凸函数: Theory/ConvexFunction.md
  - 共轭函数: Theory/ConjugateFunction.md
  - 次梯度: Theory/SubGradient.md
  - 对偶: Theory/LagrangeDual.md
- 优化算法:
  - Algorithms/Proximal.md
- HW:
  - HW1: HomeWork/HW1.md
  - HW2: HomeWork/HW2.md
  - HW3: HomeWork/HW3.md
  - HW4: HomeWork/HW4.md
  - HW5: HomeWork/HW5.md
  - HW6: HomeWork/HW6.md
  - HW7: HomeWork/HW7.md
  