[book]
authors = ["hjx"]
language = "en"
multilingual = false
src = "src"
title = "Convex Optimization"

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
mathjax-support = true

[preprocessor]

[preprocessor.pagetoc]
