[book]
authors = ["hjx"]
language = "en"
multilingual = false
src = "src"
title = "Convex Optimization"

[output.html]
mathjax-support = true

[preprocessor]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
